name: Update Sitemap Daily

on:
  schedule:
    - cron: "0 2 * * *"  # 每日台灣時間上午 10:00（UTC+8）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for url in \
            https://www.mtclouds.com/ \
            https://www.mtclouds.com/最新消息 \
            https://www.mtclouds.com/服務項目 \
            https://www.mtclouds.com/服務項目/台灣投資及工商服務 \
            https://www.mtclouds.com/服務項目/境外公司設立及管理服務 \
            https://www.mtclouds.com/服務項目/越南投資及法律諮詢 \
            https://www.mtclouds.com/服務項目/越南投資及法律諮詢/越南公司設立 \
            https://www.mtclouds.com/服務項目/越南投資及法律諮詢/商店、餐飲投資 \
            https://www.mtclouds.com/服務項目/會計師服務 \
            https://www.mtclouds.com/合作夥伴 \
            https://www.mtclouds.com/關於我們 \
            https://www.mtclouds.com/聯絡我們; do
            echo "  <url><loc>$url</loc><lastmod>$(date +%F)</lastmod></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Commit and push sitemap
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ping Google to notify sitemap update
        run: |
          curl "https://www.google.com/ping?sitemap=https://sitemap.mtclouds.com/sitemap.xml"
