name: Update Sitemap Daily

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate sitemap.xml
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' > sitemap.xml
          echo '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">' >> sitemap.xml
          for url in \
            https://www.mtclouds.com/ \
            https://www.mtclouds.com/最新消息 \
            https://www.mtclouds.com/服務項目 \
            https://www.mtclouds.com/服務項目/台灣投資及工商服務 \
            https://www.mtclouds.com/服務項目/境外公司設立及管理服務 \
            https://www.mtclouds.com/服務項目/越南投資及法律諮詢 \
            https://www.mtclouds.com/服務項目/越南投資及法律諮詢/越南公司設立 \
            https://www.mtclouds.com/服務項目/越南投資及法律諮詢/商店餐飲投資 \
            https://www.mtclouds.com/服務項目/會計師服務 \
            https://www.mtclouds.com/合作夥伴 \
            https://www.mtclouds.com/關於我們 \
            https://www.mtclouds.com/聯絡我們; do
            echo "  <url><loc>$url</loc><lastmod>$(date +%Y-%m-%d)</lastmod></url>" >> sitemap.xml
          done
          echo '</urlset>' >> sitemap.xml

      - name: Generate sitemap.html
        run: |
          echo '<!DOCTYPE html>' > sitemap.html
          echo '<html lang="zh-Hant">' >> sitemap.html
          echo '<head>' >> sitemap.html
          echo '  <meta charset="UTF-8">' >> sitemap.html
          echo '  <title>網站地圖</title>' >> sitemap.html
          echo '  <style>' >> sitemap.html
          echo '    body { font-family: sans-serif; padding: 2em; max-width: 800px; margin: auto; background: #f9f9f9; }' >> sitemap.html
          echo '    ul { list-style-type: none; padding-left: 1em; }' >> sitemap.html
          echo '    li { margin-bottom: 0.3em; }' >> sitemap.html
          echo '    a { color: #06c; text-decoration: none; }' >> sitemap.html
          echo '    a:hover { text-decoration: underline; }' >> sitemap.html
          echo '  </style>' >> sitemap.html
          echo '</head>' >> sitemap.html
          echo '<body>' >> sitemap.html
          echo '  <h1>網站地圖</h1>' >> sitemap.html
          echo '  <ul>' >> sitemap.html
          echo '    <li><a href="https://www.mtclouds.com/">首頁</a></li>' >> sitemap.html
          echo '    <li><a href="https://www.mtclouds.com/最新消息">最新消息</a></li>' >> sitemap.html
          echo '    <li>' >> sitemap.html
          echo '      <a href="https://www.mtclouds.com/服務項目">服務項目</a>' >> sitemap.html
          echo '      <ul>' >> sitemap.html
          echo '        <li><a href="https://www.mtclouds.com/服務項目/台灣投資及工商服務">台灣投資及工商服務</a></li>' >> sitemap.html
          echo '        <li><a href="https://www.mtclouds.com/服務項目/境外公司設立及管理服務">境外公司設立及管理服務</a></li>' >> sitemap.html
          echo '        <li>' >> sitemap.html
          echo '          <a href="https://www.mtclouds.com/服務項目/越南投資及法律諮詢">越南投資及法律諮詢</a>' >> sitemap.html
          echo '          <ul>' >> sitemap.html
          echo '            <li><a href="https://www.mtclouds.com/服務項目/越南投資及法律諮詢/越南公司設立">越南公司設立</a></li>' >> sitemap.html
          echo '            <li><a href="https://www.mtclouds.com/服務項目/越南投資及法律諮詢/商店餐飲投資">商店餐飲投資</a></li>' >> sitemap.html
          echo '          </ul>' >> sitemap.html
          echo '        </li>' >> sitemap.html
          echo '        <li><a href="https://www.mtclouds.com/服務項目/會計師服務">會計師服務</a></li>' >> sitemap.html
          echo '      </ul>' >> sitemap.html
          echo '    </li>' >> sitemap.html
          echo '    <li><a href="https://www.mtclouds.com/合作夥伴">合作夥伴</a></li>' >> sitemap.html
          echo '    <li><a href="https://www.mtclouds.com/關於我們">關於我們</a></li>' >> sitemap.html
          echo '    <li><a href="https://www.mtclouds.com/聯絡我們">聯絡我們</a></li>' >> sitemap.html
          echo '  </ul>' >> sitemap.html
          echo '</body>' >> sitemap.html
          echo '</html>' >> sitemap.html

      - name: Commit and push sitemap files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml sitemap.html || true
          git commit -m "Auto-update sitemap on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Ping Google to notify sitemap update
        run: |
          curl "https://www.google.com/ping?sitemap=https://sitemap.mtclouds.com/sitemap.xml"
